networks:
  frontend:
  backend:

services:
  catalog:
    image: jewels/catalogapi
    build:
      context: ./ProductCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=CatalogDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;"
      ExternalBaseUrl: "http://localhost:7000"
      ASPNETCORE_HTTP_PORTS: 80
    ports:
      - "7000:80"
      - "7001:443"
    container_name: jewelscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  tokenserver:
    image: jewels/authapi
    build:
      context: ./AuthAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=TokenServiceDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      JWT__Secret: "your_net_net_net_new_base64_encoded_key"
      JWT__Issuer: "auth-api"
      JWT__Audience: "auth-client"
    ports:
      - "7010:80"
    container_name: jewelsauthapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver
 
  cart:
    image: jewels/cartapi
    build:
      context: ./CartAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: basket.data
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      JWT__Secret: "your_net_net_net_new_base64_encoded_key"
      JWT__Issuer: "auth-api"
      JWT__Audience: "auth-client"
    ports:
      - "7020:80"
    container_name: jewelscartapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - basket.data
      - rabbitmq

  order:
    image: jewels/orderapi
    build:
      context: ./OrderAPI
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options: {
        max-size: "200k",
        max-file: "10"
      }
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=OrderDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      JWT__Secret: "your_net_net_net_new_base64_encoded_key"
      JWT__Issuer: "auth-api"
      JWT__Audience: "auth-client"
    ports:
      - "7030:80"
    container_name: jewelsorderapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - mssqlserver
      - rabbitmq

  webmvc:
    image: jewels/webmvc
    build:
      context: ./WebMVC
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options: {
        max-size: "200k",
        max-file: "10"
      }
    environment:
      CatalogUrl: http://catalog
      IdentityUrl: http://tokenserver
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_jZlpubvlPmcV6QJPReImelQy
      StripePrivateKey: sk_test_bSHT9qxwjpyCOP0qdAvHLfAA
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
    ports:
      - "7500:80"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - catalog
      - tokenserver
      - cart
      - order

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
    ports:
      - "1448:1433"
    container_name: jewelscatalogsqlserver
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "7050:6379"
    container_name: basketdata
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: jewelsrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    networks:
      - backend